const {spawn,execFile}=require('node:child_process'); const fs=require('node:fs'); const path=require('node:path'); const crypto=require('node:crypto');
const {validateConfig}=require('./configValidator.cjs'); const {buildCommand,buildTraceCommand}=require('./commandBuilder.cjs'); const {readResult}=require('./resultValidator.cjs'); const {createStore}=require('./runStore.cjs');
class RunManager {
 constructor({rootDir,userDataDir,onEvent}){this.rootDir=rootDir;this.active=null;this.onEvent=onEvent;this.store=createStore(path.join(userDataDir,'wildfire-runs'));fs.mkdirSync(path.join(rootDir,'results','live'),{recursive:true});}
 start(raw){if(this.active)throw new Error('Another benchmark is already running'); const config=validateConfig(raw); const runId=crypto.randomUUID(); const runDir=this.store.create(runId,config); const command=buildCommand(config,{rootDir:this.rootDir}); const startedAt=new Date().toISOString(); const stdout=fs.createWriteStream(path.join(runDir,'stdout.log')); const stderr=fs.createWriteStream(path.join(runDir,'stderr.log')); const child=spawn(command.file,command.args,{cwd:this.rootDir,shell:false,windowsHide:true}); this.active={runId,child,config,command,stdout,stderr,startedAt}; this.emit({type:'started',runId,backend:config.backend,startedAt}); child.stdout.on('data',b=>{const text=b.toString();stdout.write(text);this.emit({type:'log',runId,stream:'stdout',line:text.slice(-4000)})}); child.stderr.on('data',b=>{const text=b.toString();stderr.write(text);this.emit({type:'log',runId,stream:'stderr',line:text.slice(-4000)})}); child.on('error',e=>this.fail(runId,e.message)); child.on('close',(code,signal)=>this.finish(runId,code,signal)); return {runId}; }
 startTrace(raw){if(this.active)throw new Error('Another benchmark is already running'); const config=validateConfig({backend:'serial',rows:raw.rows,cols:raw.cols,steps:100,density:raw.density,seed:raw.seed,repetitions:1}); const runId=crypto.randomUUID(); const command=buildTraceCommand(config,{rootDir:this.rootDir}); const child=spawn(command.file,command.args,{cwd:this.rootDir,shell:false,windowsHide:true}); this.active={runId,child,trace:true,command}; child.on('error',e=>this.traceFail(runId,e.message)); child.on('close',(code,signal)=>this.finishTrace(runId,code,signal)); return {runId}; }
 emit(event){this.onEvent?.(event)}
 finish(runId,code,signal){const a=this.active;if(!a||a.runId!==runId)return; a.stdout.end();a.stderr.end(); if(signal){this.emit({type:'cancelled',runId});this.active=null;return;} if(code!==0){this.fail(runId,`Process exited with code ${code}`,code);return;} try{const result=readResult(a.command.outputPath,a.config);this.store.save(runId,'result.json',{runId,status:'completed',createdAt:a.startedAt,config:a.config,result});const rows=this.store.list().filter(x=>x.runId!==runId);rows.unshift({runId,status:'completed',createdAt:a.startedAt,config:a.config,result});this.store.setIndex(rows);this.emit({type:'completed',runId,result});}catch(e){this.fail(runId,e.message)}this.active=null;}
 fail(runId,message,exitCode){const a=this.active;if(!a||a.runId!==runId)return;this.emit({type:'failed',runId,message,exitCode});this.active=null;}
 finishTrace(runId,code,signal){const a=this.active;if(!a||a.runId!==runId)return;if(signal||code!==0)return this.traceFail(runId,signal?'Trace cancelled':`Trace process exited with code ${code}`);try{const trace=JSON.parse(fs.readFileSync(a.command.tracePath,'utf8'));if(trace.schemaVersion!==2||!Array.isArray(trace.frames))throw new Error('Invalid compressed trace');this.emit({type:'trace-completed',runId,trace});this.active=null;}catch(e){this.traceFail(runId,e.message)}}
 traceFail(runId,message){const a=this.active;if(!a||a.runId!==runId)return;this.emit({type:'trace-failed',runId,message});this.active=null;}
 cancel(runId){const a=this.active;if(!a||a.runId!==runId)return false; if(process.platform==='win32'&&a.child.pid){execFile('taskkill',['/PID',String(a.child.pid),'/T','/F'],{windowsHide:true},()=>{});}else a.child.kill('SIGTERM');return true;}
 list(){return this.store.list();}
 read(runId){return this.store.read(runId,'result.json');}
}
module.exports={RunManager};
