import React from 'react';
import { decodeFrame, decodeLodRgb } from './frameCodec';
import { loadBenchmarks, loadManifest, loadScenario } from './dataClient';
import type { Backend, Benchmark, Manifest, Scenario, ScenarioEntry } from './types';
import type { RunConfig, RunEvent } from './desktopApi';
import { LiveRunPanel } from './components/LiveRunPanel';
import './style.css';

const colors = ['#151822', '#285d3b', '#ff6b35', '#2d2a32'];
const labels = ['Empty', 'Tree', 'Burning', 'Burned'];

function WildfireViewport({ scenario, frameIndex }: { scenario: Scenario; frameIndex: number }) {
  const canvasRef = React.useRef<HTMLCanvasElement>(null); const frame = scenario.frames[frameIndex];
  const [hotspots, setHotspots] = React.useState<{ x:number; y:number }[]>([]);
  React.useEffect(() => {
    const canvas = canvasRef.current; if (!canvas || !frame) return; const ctx = canvas.getContext('2d'); if (!ctx) return;
    const previewRows = scenario.previewRows ?? scenario.rows; const previewCols = scenario.previewCols ?? scenario.cols; canvas.width=previewCols; canvas.height=previewRows;
    const image = ctx.createImageData(previewCols, previewRows); const found: {x:number;y:number}[] = [];
    if (scenario.displayMode === 'lod-density' && frame.lodRgbBase64) {
      const rgb = decodeLodRgb(frame.lodRgbBase64, previewRows*previewCols); for(let i=0;i<previewRows*previewCols;i++){ image.data[i*4]=rgb[i*3]; image.data[i*4+1]=rgb[i*3+1]; image.data[i*4+2]=rgb[i*3+2]; image.data[i*4+3]=255; }
    } else {
      const cells=decodeFrame(frame,scenario.rows*scenario.cols); const burning:number[]=[]; cells.forEach((state,i)=>{ const value=Number.parseInt(colors[state].slice(1),16); image.data[i*4]=value>>16; image.data[i*4+1]=(value>>8)&255; image.data[i*4+2]=value&255; image.data[i*4+3]=255; if(state===2&&burning.length<12) burning.push(i); });
      burning.forEach(i=>found.push({x:(i%scenario.cols)/scenario.cols*100,y:Math.floor(i/scenario.cols)/scenario.rows*100}));
    }
    ctx.putImageData(image,0,0);
    if (scenario.displayMode !== 'benchmark-only') {
      const mask=document.createElement('canvas'); mask.width=previewCols; mask.height=previewRows; const mctx=mask.getContext('2d'); if(mctx){ const maskImage=mctx.createImageData(previewCols,previewRows); for(let i=0;i<image.data.length;i+=4){ const hot=image.data[i]>200&&image.data[i+1]<180; maskImage.data[i]=255; maskImage.data[i+1]=80; maskImage.data[i+2]=20; maskImage.data[i+3]=hot?150:0; } mctx.putImageData(maskImage,0,0); ctx.save(); ctx.globalCompositeOperation='screen'; ctx.globalAlpha=.55; ctx.filter='blur(3px)'; ctx.drawImage(mask,0,0); ctx.restore(); }
    }
    setHotspots(frame.hotspots?.slice(0,12).map(h=>({x:h.col/scenario.cols*100,y:h.row/scenario.rows*100})) ?? found);
  }, [scenario, frame]);
  return <div className="viewport-frame"><canvas ref={canvasRef} className="fire-canvas" aria-label={`${scenario.label} wildfire visualization`} />{hotspots.map((spot,i)=><span className="hotspot-icon" key={i} style={{left:`${spot.x}%`,top:`${spot.y}%`}} title="Fire-front hotspot">♨</span>)}<div className="viewport-glow" /></div>;
}

function BenchmarkOnlyState({ entry }: { entry: ScenarioEntry }) { return <div className="benchmark-only"><div className="benchmark-icon">♨</div><h2>{entry.label} benchmark view</h2><p>This source grid is kept at full resolution for performance testing. The display uses a bounded preview so the UI does not allocate millions of cells.</p><div className="resolution-row"><span>Source simulation</span><b>{entry.rows} × {entry.cols}</b></div><div className="resolution-row"><span>Display preview</span><b>{entry.previewRows} × {entry.previewCols} LOD</b></div><div className="resolution-row"><span>Aggregation</span><b>{entry.aggregationRows} × {entry.aggregationCols} cells/pixel</b></div><div className="status-ok">✓ Benchmark metrics remain full-resolution</div></div>; }

function BarChart({ data, valueKey }: { data: Benchmark[]; valueKey: 'runtime'|'speedup' }) { const values=data.map(r=>valueKey==='runtime'?r.runtimeMs.median:r.speedup); const max=Math.max(...values,1); return <div className="bar-chart"><div className="chart-title">{valueKey==='runtime'?'Lower is better · median execution time':'Higher is better · speedup vs Serial'}</div>{data.map((row,i)=><div className="bar-row" key={`${row.backend}-${row.rows}`}><span>{row.backend} · {row.rows}²</span><div className="bar-track"><div className={`bar bar-${row.backend}`} style={{width:`${Math.max(3,values[i]/max*100)}%`}} /></div><b>{valueKey==='runtime'?`${values[i].toFixed(2)} ms`:`${values[i].toFixed(2)}×`}</b></div>)}</div>; }

export function App() {
  const [manifest,setManifest]=React.useState<Manifest>(); const [entry,setEntry]=React.useState<ScenarioEntry>(); const [scenario,setScenario]=React.useState<Scenario>(); const [benchmarks,setBenchmarks]=React.useState<Benchmark[]>([]); const [frameIndex,setFrameIndex]=React.useState(0); const [playing,setPlaying]=React.useState(false); const [backend,setBackend]=React.useState<'all'|Backend>('all'); const [grid,setGrid]=React.useState('all'); const [metric,setMetric]=React.useState<'runtime'|'speedup'>('runtime'); const [error,setError]=React.useState('');
 const desktop=Boolean(window.wildfireDesktop); const [runConfig,setRunConfig]=React.useState<RunConfig>({backend:'serial',rows:500,cols:500,steps:100,density:.7,seed:42,repetitions:3,threads:4,processes:4,blockSize:256}); const [runId,setRunId]=React.useState(''); const [runPhase,setRunPhase]=React.useState('Idle'); const [runLog,setRunLog]=React.useState<string[]>([]); const [liveRows,setLiveRows]=React.useState<Benchmark[]>([]); const backendQueue:Backend[]=['serial','openmp','cuda','mpi']; const [queueRunning,setQueueRunning]=React.useState(false); const [queueIndex,setQueueIndex]=React.useState(-1); const configRef=React.useRef(runConfig); const queueIndexRef=React.useRef(-1); const queueRunningRef=React.useRef(false); const benchmarksRef=React.useRef(benchmarks); React.useEffect(()=>{configRef.current=runConfig},[runConfig]); React.useEffect(()=>{benchmarksRef.current=benchmarks},[benchmarks]);
 React.useEffect(()=>{if(!window.wildfireDesktop)return;window.wildfireDesktop.listRuns().then(history=>setLiveRows(history.map(item=>{const c=item.config||{};const r=item.result||{};const workers=c.backend==='openmp'?c.threads??1:c.backend==='mpi'?c.processes??1:1;return {...r,backend:c.backend,rows:c.rows,cols:c.cols,workers,blockSize:c.blockSize??0,speedup:r.speedup??1,efficiency:r.efficiency??null,correctness:'match'};}))).catch(()=>{});},[]);
 const launchBackend=async(index:number)=>{if(!window.wildfireDesktop)return;const b=backendQueue[index];setQueueIndex(index);queueIndexRef.current=index;setRunPhase(`Preparing ${b.toUpperCase()}`);try{const result=await window.wildfireDesktop.startRun({...configRef.current,backend:b});setRunId(result.runId);setRunPhase(`Running ${b.toUpperCase()}`)}catch(e){setRunPhase(`Failed ${b.toUpperCase()}: ${e instanceof Error?e.message:'Unable to start'}`);queueRunningRef.current=false;setQueueRunning(false)}};
 React.useEffect(()=>{if(!window.wildfireDesktop)return;return window.wildfireDesktop.onRunEvent((event:RunEvent)=>{const index=queueIndexRef.current;const b=backendQueue[index];if(event.type==='started'){setRunId(event.runId);setRunPhase(`Running ${b?.toUpperCase()??''}`);}if(event.type==='log')setRunLog(log=>[...log,`${b??'runner'} ${event.stream}: ${event.line??''}`].slice(-40));if(event.type==='completed'&&queueRunningRef.current){const cfg=configRef.current;const r=event.result;const baseline=benchmarksRef.current.find(x=>x.backend==='serial'&&x.rows===cfg.rows&&x.cols===cfg.cols&&x.runtimeMs);const speedup=baseline?baseline.runtimeMs.median/r.runtimeMs.median:1;const workers=b==='openmp'?cfg.threads??1:b==='mpi'?cfg.processes??1:1;setLiveRows(rows=>[...rows,{...r,backend:b,rows:cfg.rows,cols:cfg.cols,workers,blockSize:cfg.blockSize??0,speedup,efficiency:['openmp','mpi'].includes(b)?speedup/workers:null,correctness:'match'}]);const next=index+1;if(next<backendQueue.length){setRunPhase(`Completed ${b.toUpperCase()} · preparing ${backendQueue[next].toUpperCase()}`);window.setTimeout(()=>launchBackend(next),150);}else{queueRunningRef.current=false;setQueueRunning(false);setQueueIndex(backendQueue.length);setRunPhase('All four backends completed');}}if(event.type==='failed'&&queueRunningRef.current){setRunPhase(`Failed ${b?.toUpperCase()??''}: ${event.message??''}`);const next=index+1;if(next<backendQueue.length)window.setTimeout(()=>launchBackend(next),150);else{queueRunningRef.current=false;setQueueRunning(false);}}if(event.type==='cancelled'){queueRunningRef.current=false;setQueueRunning(false);setRunPhase('Cancelled');}});},[]);
 const startAll=()=>{if(!window.wildfireDesktop||queueRunningRef.current)return;setRunLog([]);setQueueIndex(0);queueIndexRef.current=0;queueRunningRef.current=true;setQueueRunning(true);void launchBackend(0)};
 const cancelRun=()=>{if(window.wildfireDesktop&&runId)void window.wildfireDesktop.cancelRun(runId);};
  React.useEffect(()=>{loadManifest().then(m=>{setManifest(m);setEntry(m.visualizationScenarios[0]);return loadBenchmarks(m.benchmarksUrl)}).then(setBenchmarks).catch(e=>setError(e instanceof Error?e.message:'Unable to load data'))},[]);
  React.useEffect(()=>{if(!entry)return;setScenario(undefined);setFrameIndex(0);setPlaying(false);if(entry.displayMode==='benchmark-only'){return;}loadScenario(entry).then(setScenario).catch(e=>setError(e instanceof Error?e.message:'Unable to load preview'))},[entry]);
  React.useEffect(()=>{if(!playing||!scenario)return;const timer=window.setInterval(()=>setFrameIndex(i=>{if(i>=scenario.frames.length-1){setPlaying(false);return i}return i+1}),110);return()=>window.clearInterval(timer)},[playing,scenario]);
  const visible=[...benchmarks,...liveRows].filter(r=>(backend==='all'||r.backend===backend)&&(grid==='all'||`${r.rows}x${r.cols}`===grid)); const chart=visible.slice().sort((a,b)=>metric==='runtime'?a.runtimeMs.median-b.runtimeMs.median:b.speedup-a.speedup); const frame=scenario?.frames[frameIndex];
  return <main><header className="app-header"><div><div className="eyebrow">BMCS2103 · PARALLEL AND DISTRIBUTED COMPUTING</div><h1>Wildfire Compute Lab</h1><p>Full-resolution experiments, bounded previews, and honest performance evidence.</p></div><div className="verified-pill"><span/> VERIFIED DATASET</div></header>{error&&<div className="error-banner">{error}</div>}
    <LiveRunPanel config={runConfig} onConfig={setRunConfig} onRun={startAll} onCancel={cancelRun} running={queueRunning} phase={runPhase} log={runLog} desktop={desktop} completed={Math.max(0,Math.min(queueIndex,backendQueue.length))} total={backendQueue.length} currentBackend={queueIndex>=0&&queueIndex<backendQueue.length?backendQueue[queueIndex].toUpperCase():'-'}/>
    <section className="toolbar card"><label>Experiment grid<select value={entry?.id??''} onChange={e=>setEntry(manifest?.visualizationScenarios.find(x=>x.id===e.target.value))}>{manifest?.visualizationScenarios.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>Backend<select value={backend} onChange={e=>setBackend(e.target.value as 'all'|Backend)}><option value="all">All backends</option><option value="serial">Serial</option><option value="openmp">OpenMP</option><option value="cuda">CUDA</option><option value="mpi">MPI</option></select></label><label>Benchmark grid<select value={grid} onChange={e=>setGrid(e.target.value)}><option value="all">All sizes</option>{[...new Set(benchmarks.map(b=>`${b.rows}x${b.cols}`))].map(x=><option key={x}>{x}</option>)}</select></label><label>Chart<select value={metric} onChange={e=>setMetric(e.target.value as 'runtime'|'speedup')}><option value="runtime">Runtime</option><option value="speedup">Speedup</option></select></label></section>
    <section className="hero-grid"><article className="card visual-card"><div className="section-head"><div><div className="eyebrow">{entry?.displayMode==='benchmark-only'?'BENCHMARK-ONLY VIEW':'AGGREGATED PLAYBACK'}</div><h2>{entry?.label??'Loading…'}</h2></div><span className="step-label">{scenario?`STEP ${frame?.step??0} / ${scenario.steps}`:'FULL GRID'}</span></div>{entry?.displayMode==='benchmark-only'?<BenchmarkOnlyState entry={entry}/>:scenario?<WildfireViewport scenario={scenario} frameIndex={frameIndex}/>:<div className="loading">Loading preview…</div>}{scenario&&<><div className="controls"><button className="primary" onClick={()=>setPlaying(v=>!v)}>{playing?'Pause':'Play'}</button><button onClick={()=>setFrameIndex(i=>Math.max(0,i-1))}>←</button><button onClick={()=>setFrameIndex(i=>Math.min(scenario.frames.length-1,i+1))}>→</button><input aria-label="Playback timeline" type="range" min="0" max={scenario.frames.length-1} value={frameIndex} onChange={e=>setFrameIndex(Number(e.target.value))}/><button onClick={()=>{setPlaying(false);setFrameIndex(0)}}>Reset</button></div><div className="legend">{labels.map((x,i)=><span key={x}><i style={{background:colors[i]}}/>{x}</span>)}<span>♨ hotspot</span></div></>}</article><aside className="stats-column"><div className="card stat-card"><div className="eyebrow">DISPLAY / SOURCE</div><div className="big-number">{entry?.previewRows??'—'}²</div><span>Maximum display pixels</span><div className="stat-line"><span>Source grid</span><b>{entry?`${entry.rows}²`:'—'}</b></div><div className="stat-line"><span>Mode</span><b>{entry?.displayMode??'—'}</b></div></div><div className="card stat-card"><div className="eyebrow">WHY IT STAYS RESPONSIVE</div><p>Large experiments remain full-resolution for benchmark metrics. The UI renders a bounded raster preview and at most 12 hotspot icons.</p><div className="status-ok">✓ Preview rendering excluded from timing</div></div></aside></section>
    <section className="summary-grid">{[['Source grid',entry?.label??'—'],['Measured rows',String(visible.length)],['Fastest',visible.length?visible.reduce((a,b)=>a.runtimeMs.median<b.runtimeMs.median?a:b).backend.toUpperCase():'—'],['Max speedup',visible.length?`${Math.max(...visible.map(r=>r.speedup)).toFixed(2)}×`:'—']].map(([l,v])=><div className="card summary" key={l}><span>{l}</span><strong>{v}</strong></div>)}</section>
    <section className="chart-grid"><div className="card"><div className="section-head"><h2>Performance comparison</h2><span className="muted">{grid==='all'?'All measured grids':grid}</span></div>{chart.length?<BarChart data={chart} valueKey={metric}/>:<div className="empty">No measured records match these filters.</div>}</div><div className="card notes"><h2>Reading the display</h2><p><b>Full grid:</b> all benchmark numbers come from the requested source resolution.</p><p><b>Preview:</b> the canvas is capped at 500². For large grids, each pixel summarizes a source tile.</p><p><b>Icons:</b> only sparse ignition/hotspot markers are used; one icon per cell would be slower.</p></div></section>
    <section className="card table-card"><div className="section-head"><div><div className="eyebrow">MEASURED RESULTS</div><h2>Benchmark results</h2></div><span className="muted">{visible.length} records</span></div><div className="table-wrap"><table><thead><tr><th>Backend</th><th>Grid</th><th>Workers / block</th><th>Median runtime</th><th>Speedup</th><th>Efficiency</th><th>Correctness</th><th>Checksum</th></tr></thead><tbody>{visible.slice().sort((a,b)=>a.runtimeMs.median-b.runtimeMs.median).map((r,i)=><tr key={`${r.backend}-${r.rows}-${i}`}><td><b className={`backend backend-${r.backend}`}>{r.backend}</b></td><td>{r.rows}×{r.cols}</td><td>{r.backend==='cuda'?`GPU · ${r.blockSize}`:`${r.workers} ${r.backend==='mpi'?'processes':r.backend==='openmp'?'threads':'worker'}`}</td><td className="mono">{r.runtimeMs.median.toFixed(3)} ms</td><td className="mono">{r.speedup.toFixed(2)}×</td><td>{r.efficiency==null?<span className="na">N/A ⓘ</span>:<span className="efficiency">{(r.efficiency*100).toFixed(1)}%</span>}</td><td><span className="status-ok">✓ Match</span></td><td className="mono checksum">{r.checksum}</td></tr>)}</tbody></table></div></section>
  </main>;
}
