import React from 'react';
import { loadBenchmarks, loadManifest, loadScenario } from './dataClient';
import type { Backend, Benchmark, Manifest, Scenario } from './types';
import type { RunConfig, RunEvent } from './desktopApi';
import { BACKEND_ORDER, buildSelectedConfigs, FIXED_RUN_SETTINGS } from './runConfig';
import { LiveRunPanel } from './components/LiveRunPanel';
import { FourBackendTimeComparison } from './components/FourBackendTimeComparison';
import './style.css';

const names: Record<Backend, string> = { serial: 'Serial', openmp: 'OpenMP', cuda: 'CUDA', mpi: 'MPI' };
const baseConfig: RunConfig = { backend: 'serial', rows: 500, cols: 500, steps: 100, density: .7, seed: 42, repetitions: 3, threads: 4, processes: 4, blockSize: 256 };
function BarChart({ data }: { data: Benchmark[] }) { const max = Math.max(...data.map((row) => row.runtimeMs.median), 1); return <div className="bar-chart">{data.map((row) => <div className="bar-row" key={`${row.backend}-${row.rows}`}><span>{names[row.backend]}</span><div className="bar-track"><div className={`bar bar-${row.backend}`} style={{ width: `${Math.max(3, row.runtimeMs.median / max * 100)}%` }} /></div><b>{row.runtimeMs.median.toFixed(2)} ms</b></div>)}</div>; }
export function App() {
  const desktop = Boolean(window.wildfireDesktop); const [manifest, setManifest] = React.useState<Manifest>(); const [scenario, setScenario] = React.useState<Scenario>(); const [benchmarks, setBenchmarks] = React.useState<Benchmark[]>([]); const [runConfig, setRunConfig] = React.useState(baseConfig); const [selected, setSelected] = React.useState<Backend[]>([...BACKEND_ORDER]); const [liveRows, setLiveRows] = React.useState<Benchmark[]>([]); const [runId, setRunId] = React.useState(''); const [phase, setPhase] = React.useState('Idle'); const [log, setLog] = React.useState<string[]>([]); const [queueRunning, setQueueRunning] = React.useState(false); const [completed, setCompleted] = React.useState(0); const [frameIndex, setFrameIndex] = React.useState(0); const [error, setError] = React.useState('');
  const queueRef = React.useRef<RunConfig[]>([]); const indexRef = React.useRef(-1); const runningRef = React.useRef(false); const configRef = React.useRef(runConfig); const selectedRef = React.useRef(selected); const liveRef = React.useRef(liveRows);
  React.useEffect(() => { configRef.current = runConfig; }, [runConfig]); React.useEffect(() => { selectedRef.current = selected; }, [selected]); React.useEffect(() => { liveRef.current = liveRows; }, [liveRows]);
  React.useEffect(() => { loadManifest().then((m) => { setManifest(m); return Promise.all([loadBenchmarks(m.benchmarksUrl), m.visualizationScenarios[0] ? loadScenario(m.visualizationScenarios[0]) : Promise.resolve(undefined)]); }).then(([rows, trace]) => { setBenchmarks(rows); setScenario(trace); }).catch((e) => setError(e instanceof Error ? e.message : 'Unable to load dashboard data')); }, []);
  React.useEffect(() => { if (!desktop) return; return window.wildfireDesktop?.onRunEvent((event: RunEvent) => { const config = queueRef.current[indexRef.current]; const backend = config?.backend ?? event.backend as Backend; if (event.type === 'started') { setRunId(event.runId); setPhase(`Running ${names[backend]}`); } if (event.type === 'log') setLog((lines) => [...lines, `${names[backend] ?? 'runner'} ${event.stream}: ${event.line ?? ''}`].slice(-40)); if (event.type === 'completed') { const result = event.result as Benchmark; const baseline = [...liveRef.current, ...benchmarks].find((row) => row.backend === 'serial' && row.rows === config.rows && row.cols === config.cols); const speedup = baseline ? baseline.runtimeMs.median / result.runtimeMs.median : 1; const row = { ...result, backend, rows: config.rows, cols: config.cols, steps: 100, workers: backend === 'openmp' ? 4 : backend === 'mpi' ? 4 : 1, blockSize: backend === 'cuda' ? 256 : 0, speedup, efficiency: ['openmp', 'mpi'].includes(backend) ? speedup / 4 : null, correctness: 'match' as const }; setLiveRows((rows) => [...rows.filter((item) => !(item.backend === backend && item.rows === config.rows)), row]); advanceQueue(); } if (event.type === 'failed') { setPhase(`Failed ${names[backend]} · continuing`); advanceQueue(); } if (event.type === 'cancelled') { runningRef.current = false; setQueueRunning(false); setPhase('Cancelled'); } }); }, [desktop, benchmarks]);
  const launch = React.useCallback((index: number) => { const config = queueRef.current[index]; if (!config || !window.wildfireDesktop) return; indexRef.current = index; setPhase(`Preparing ${names[config.backend]}`); window.wildfireDesktop.startRun(config).catch((e) => { setPhase(`Failed ${names[config.backend]} · continuing`); advanceQueue(); }); }, []);
  const advanceQueue = React.useCallback(() => { const next = indexRef.current + 1; setCompleted(next); if (next < queueRef.current.length && runningRef.current) { window.setTimeout(() => launch(next), 100); } else { runningRef.current = false; setQueueRunning(false); setPhase(`${queueRef.current.length} selected methods finished`); } }, [launch]);
  const start = () => { if (!desktop || runningRef.current) return; try { queueRef.current = buildSelectedConfigs({ rows: runConfig.rows, density: runConfig.density, methods: selectedRef.current }); } catch (e) { setPhase(e instanceof Error ? e.message : 'Select at least one method'); return; } setLog([]); setCompleted(0); setLiveRows([]); runningRef.current = true; setQueueRunning(true); launch(0); };
  const cancel = () => { if (runId && window.wildfireDesktop) void window.wildfireDesktop.cancelRun(runId); };
  const activeRows = liveRows.length ? liveRows : benchmarks.filter((row) => selected.includes(row.backend) && row.rows === runConfig.rows && row.cols === runConfig.cols); const chart = activeRows.slice().sort((a, b) => a.runtimeMs.median - b.runtimeMs.median);
  return <main><header className="app-header"><div><div className="eyebrow">BMCS2103 · PARALLEL AND DISTRIBUTED COMPUTING</div><h1>Wildfire Compute Lab</h1><p>Isolated backend runs, a bounded majority-state preview, and honest synchronized playback.</p></div><div className="verified-pill"><span /> VERIFIED DATASET</div></header>{error && <div className="error-banner">{error}</div>}
    <LiveRunPanel config={runConfig} onConfig={setRunConfig} selected={selected} onSelected={setSelected} onRun={start} onCancel={cancel} running={queueRunning} phase={phase} log={log} desktop={desktop} completed={completed} total={queueRef.current.length || selected.length} currentBackend={queueRef.current[indexRef.current]?.backend ?? '-'} />
    <FourBackendTimeComparison records={activeRows} rows={runConfig.rows} steps={FIXED_RUN_SETTINGS.steps} selected={selected} scenario={scenario} frameIndex={frameIndex} />
    <section className="card trace-status"><div className="section-head"><div><div className="eyebrow">PREVIEW CONTRACT</div><h2>Bounded deterministic trace</h2></div><span className="muted">Canvas backing: 500 × 500</span></div><p>Source: {runConfig.rows}×{runConfig.rows} · Display: 500×500 · {Math.max(1, runConfig.rows / 500)}×{Math.max(1, runConfig.rows / 500)} cells/pixel · majority-state. The same trace is shared by every backend tile.</p></section>
    <section className="summary-grid">{[['Source grid', `${runConfig.rows}²`], ['Active results', String(activeRows.length)], ['Fastest', activeRows.length ? names[activeRows.reduce((a, b) => a.runtimeMs.median < b.runtimeMs.median ? a : b).backend] : '—'], ['Max speedup', activeRows.length ? `${Math.max(...activeRows.map((row) => row.speedup)).toFixed(2)}×` : '—']].map(([label, value]) => <div className="card summary" key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>
    <section className="chart-grid"><div className="card"><div className="section-head"><h2>Active batch performance</h2><span className="muted">No user filters</span></div>{chart.length ? <BarChart data={chart} /> : <div className="empty">Run selected methods to populate active batch results.</div>}</div><div className="card notes"><h2>Reading the display</h2><p><b>Trace:</b> all tiles use the same deterministic fire trace.</p><p><b>Timing:</b> each tile's progress is positioned using its isolated median runtime, not live hardware telemetry.</p><p><b>Large grids:</b> the canvas remains 500×500 and each pixel represents a majority-state source tile.</p></div></section>
    <section className="card table-card"><div className="section-head"><div><div className="eyebrow">ACTIVE BATCH RESULTS</div><h2>Benchmark results</h2></div><span className="muted">{activeRows.length} records</span></div><div className="table-wrap"><table><thead><tr><th>Backend</th><th>Grid</th><th>Workers / block</th><th>Median runtime</th><th>Speedup</th><th>Efficiency</th><th>Correctness</th><th>Checksum</th></tr></thead><tbody>{chart.map((row, index) => <tr key={`${row.backend}-${row.rows}-${index}`}><td><b className={`backend backend-${row.backend}`}>{names[row.backend]}</b></td><td>{row.rows}×{row.cols}</td><td>{row.backend === 'cuda' ? `GPU · ${row.blockSize}` : `${row.workers} ${row.backend === 'mpi' ? 'processes' : row.backend === 'openmp' ? 'threads' : 'worker'}`}</td><td className="mono">{row.runtimeMs.median.toFixed(3)} ms</td><td className="mono">{row.speedup.toFixed(2)}×</td><td>{row.efficiency == null ? <span className="na">N/A</span> : `${(row.efficiency * 100).toFixed(1)}%`}</td><td><span className="status-ok">✓ Match</span></td><td className="mono checksum">{row.checksum}</td></tr>)}</tbody></table></div></section>
  </main>;
}
