import React from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

type Frame = { step: number; cells: number[] };
type Scenario = { rows: number; cols: number; frames: Frame[] };
type Benchmark = { backend: string; rows: number; cols: number; workers: number; blockSize: number; runtimeMs: { median: number }; speedup: number; efficiency: number | null; burnedCells: number; checksum: string };

const colors = ['#20242b', '#3f9b52', '#ff6b22', '#2e3035'];

function CanvasView({ scenario, frame }: { scenario: Scenario; frame: Frame | undefined }) {
  const ref = React.useRef<HTMLCanvasElement>(null);
  React.useEffect(() => {
    const canvas = ref.current; if (!canvas || !frame) return;
    const ctx = canvas.getContext('2d'); if (!ctx) return;
    canvas.width = scenario.cols; canvas.height = scenario.rows;
    const image = ctx.createImageData(scenario.cols, scenario.rows);
    frame.cells.forEach((state, i) => { const hex = colors[state] ?? colors[0]; const value = parseInt(hex.slice(1), 16); image.data[i*4] = value >> 16; image.data[i*4+1] = (value >> 8) & 255; image.data[i*4+2] = value & 255; image.data[i*4+3] = 255; });
    ctx.putImageData(image, 0, 0);
  }, [scenario, frame]);
  return <canvas ref={ref} className="fire-canvas" aria-label="Wildfire simulation canvas" />;
}

function App() {
  const [scenario, setScenario] = React.useState<Scenario | null>(null);
  const [benchmarks, setBenchmarks] = React.useState<Benchmark[]>([]);
  const [index, setIndex] = React.useState(0);
  const [playing, setPlaying] = React.useState(false);
  const [error, setError] = React.useState('');
  React.useEffect(() => { Promise.all([fetch('/data/demo_serial.json').then(r => r.json()), fetch('/data/benchmarks.json').then(r => r.json())]).then(([s, b]) => { setScenario(s); setBenchmarks(b); }).catch(() => setError('Dashboard data is missing. Run the demo-data preparation command first.')); }, []);
  React.useEffect(() => { if (!playing || !scenario) return; const id = window.setInterval(() => setIndex(i => { if (i + 1 >= scenario.frames.length) { setPlaying(false); return i; } return i + 1; }), 100); return () => window.clearInterval(id); }, [playing, scenario]);
  const frame = scenario?.frames[index];
  return <main><header><p className="eyebrow">BMCS2103 · PARALLEL AND DISTRIBUTED COMPUTING</p><h1>Wildfire Parallelisation Lab</h1><p className="subtitle">Precomputed cellular-automata playback and reproducible performance evidence.</p></header>
    {error && <div className="notice">{error}</div>}
    <section className="layout"><article className="card visual"><div className="card-head"><h2>Simulation Playback</h2><span>{scenario ? `${scenario.rows}×${scenario.cols}` : '—'}</span></div>{scenario && <CanvasView scenario={scenario} frame={frame} />}<div className="controls"><button onClick={() => setPlaying(v => !v)}>{playing ? 'Pause' : 'Play'}</button><button onClick={() => setIndex(i => Math.max(0, i - 1))}>Step −</button><button onClick={() => setIndex(i => Math.min((scenario?.frames.length ?? 1)-1, i + 1))}>Step +</button><input type="range" min="0" max={(scenario?.frames.length ?? 1)-1} value={index} onChange={e => setIndex(Number(e.target.value))}/></div><div className="legend">{['Empty','Tree','Burning','Burned'].map((label, i) => <span key={label}><i style={{background: colors[i]}} />{label}</span>)}</div></article>
    <article className="card stats"><h2>Current Frame</h2><div className="metric"><strong>{frame?.step ?? '—'}</strong><span>Timestep</span></div><div className="metric"><strong>{frame ? frame.cells.filter(x => x === 2).length : '—'}</strong><span>Burning cells</span></div><div className="metric"><strong>{frame ? frame.cells.filter(x => x === 3).length : '—'}</strong><span>Burned cells</span></div><p className="muted">Animation data is generated by the C++ backend. Rendering time is not included in benchmark timing.</p></article></section>
    <section className="card"><div className="card-head"><h2>Benchmark Results</h2><span>{benchmarks.length} records</span></div><div className="table-wrap"><table><thead><tr><th>Backend</th><th>Grid</th><th>Workers</th><th>Median ms</th><th>Speedup</th><th>Efficiency</th><th>Checksum</th></tr></thead><tbody>{benchmarks.map((b, i) => <tr key={i}><td><b>{b.backend}</b></td><td>{b.rows}×{b.cols}</td><td>{b.workers}{b.blockSize ? ` / block ${b.blockSize}` : ''}</td><td>{b.runtimeMs.median.toFixed(3)}</td><td>{b.speedup.toFixed(2)}×</td><td>{b.efficiency == null ? '—' : `${(b.efficiency*100).toFixed(1)}%`}</td><td className="checksum">{b.checksum}</td></tr>)}</tbody></table></div></section>
  </main>;
}
createRoot(document.getElementById('root')!).render(<App />);
