import React from 'react';
import type { Backend, Benchmark, Scenario } from '../types';
import type { LiveTrace } from '../desktopApi';
import { bitMaskHasAny, decodeBitMask, decodeFrame } from '../frameCodec';
import { aggregationForGrid, firstSampledExtinguishedStep, FIXED_TIME_PLAYBACK, rawStepAtVirtualTime, stepsPerSecond } from '../runConfig';

const ORDER: Backend[] = ['serial', 'openmp', 'cuda', 'mpi'];
const COLORS = ['#151822', '#285d3b', '#ff6b35', '#2d2a32'];
const LABELS: Record<Backend, string> = { serial: 'Serial', openmp: 'OpenMP', cuda: 'CUDA', mpi: 'MPI' };
type Props = { records: Benchmark[]; rows: number; density:number; seed:number; traceSteps:number; steps: number; selected: Backend[]; scenario?: Scenario; liveTrace?: LiveTrace; frameIndex: number };

function frameAtOrBefore(frames: {step:number}[], step: number): number { let low=0, high=frames.length-1, answer=0; while(low<=high){const mid=(low+high)>>1;if(frames[mid].step<=step){answer=mid;low=mid+1;}else high=mid-1;} return answer; }
function FireCanvas({ scenario, frameIndex, label }: { scenario?: Pick<Scenario | LiveTrace, 'frames'>; frameIndex: number; label: string }) {
  const ref=React.useRef<HTMLCanvasElement>(null);
  React.useEffect(()=>{const canvas=ref.current, frame=scenario?.frames[frameIndex]; if(!canvas||!frame)return; canvas.width=500;canvas.height=500;const ctx=canvas.getContext('2d');if(!ctx)return;try{const cells=decodeFrame(frame,250000);const mask=frame.burningMaskBase64?decodeBitMask(frame.burningMaskBase64,250000):undefined;const image=ctx.createImageData(500,500);for(let i=0;i<cells.length;i+=1){const color=Number.parseInt((mask?.[i]?'#ff8a24':COLORS[cells[i]]).slice(1),16);image.data[i*4]=color>>16;image.data[i*4+1]=(color>>8)&255;image.data[i*4+2]=color&255;image.data[i*4+3]=255;}ctx.putImageData(image,0,0);}catch{ctx.fillStyle=COLORS[0];ctx.fillRect(0,0,500,500);}},[scenario,frameIndex]);
  return <canvas ref={ref} className="backend-fire-canvas" width={500} height={500} aria-label={`${label} shared deterministic fire trace`}/>;
}
export function FourBackendTimeComparison({records,rows,density,seed,traceSteps,selected,scenario,liveTrace}:Props){
  const trace=liveTrace?.sourceRows===rows&&liveTrace.sourceCols===rows&&liveTrace.density===density&&liveTrace.seed===seed&&liveTrace.steps===traceSteps?liveTrace:undefined; // never reuse a stale/static trace for another selected grid
  const fireByFrame=React.useMemo(()=>trace?trace.frames.map(frame=>{try{return bitMaskHasAny(frame.burningMaskBase64,250000)}catch{return false}}):[],[trace]);
  const extinguishedStep=React.useMemo(()=>trace?firstSampledExtinguishedStep(trace.frames,fireByFrame):undefined,[trace,fireByFrame]);
  const successful=records.filter(r=>selected.includes(r.backend)&&r.rows===rows&&r.cols===rows); const serial=successful.find(r=>r.backend==='serial');
  const [time,setTime]=React.useState(0),[playing,setPlaying]=React.useState(false); const last=React.useRef(0);
  const playbackKey=`${rows}:${selected.join(',')}:${liveTrace?.density??'none'}:${liveTrace?.frames.length??0}:${successful.map(row=>`${row.backend}:${row.runtimeMs.median}`).join('|')}`;
  React.useEffect(()=>{setPlaying(false);setTime(0);},[playbackKey]);
  React.useEffect(()=>{if(!playing)return;last.current=performance.now();let id=0;const tick=(now:number)=>{const delta=now-last.current;last.current=now;setTime(v=>{const next=Math.min(FIXED_TIME_PLAYBACK.virtualWindowMs,v+delta*FIXED_TIME_PLAYBACK.virtualWindowMs/FIXED_TIME_PLAYBACK.screenDurationMs);if(next>=FIXED_TIME_PLAYBACK.virtualWindowMs)setPlaying(false);return next;});id=requestAnimationFrame(tick);};id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id);},[playing]);
  return <section className="card time-comparison"><div className="section-head"><div><div className="eyebrow">FIXED 5-SECOND VIRTUAL-TIME COMPARISON</div><h2>Step-throughput playback</h2></div><span className="muted">10 s on-screen playback</span></div><p className="muted">Step positions are derived from isolated 100-step medians. Shared deterministic native trace · not live hardware telemetry.</p>
  <div className="time-controls"><button className="primary" onClick={()=>setPlaying(v=>!v)} disabled={!trace||!successful.length}>{playing?'Pause':'Play'}</button><button onClick={()=>{setPlaying(false);setTime(0)}}>Reset</button><input aria-label="Master playback timeline" type="range" min="0" max={FIXED_TIME_PLAYBACK.virtualWindowMs} step="10" value={time} onChange={e=>{setPlaying(false);setTime(Number(e.target.value))}}/><b>{(time/1000).toFixed(1)} / 5.0 s virtual</b></div>
  <div className="backend-comparison-grid">{ORDER.map(backend=>{if(!selected.includes(backend))return <div className="backend-tile missing" key={backend}><b>{LABELS[backend]}</b><span>Not selected for this batch</span></div>;const row=successful.find(r=>r.backend===backend);if(!row)return <div className="backend-tile missing" key={backend}><b>{LABELS[backend]}</b><span>Benchmark unavailable or failed</span></div>;const derivedStep=rawStepAtVirtualTime(time,row.runtimeMs.median),finalDerived=rawStepAtVirtualTime(FIXED_TIME_PLAYBACK.virtualWindowMs,row.runtimeMs.median),traceFinal=trace?.frames[trace.frames.length-1]?.step??0,extinguished=extinguishedStep!==undefined&&derivedStep>=extinguishedStep,visualStep=extinguished?extinguishedStep:Math.min(derivedStep,traceFinal),index=trace?frameAtOrBefore(trace.frames,visualStep):0,fire=fireByFrame[index]??false,fps=stepsPerSecond(row.runtimeMs.median);const relative=serial?stepsPerSecond(serial.runtimeMs.median)?fps/stepsPerSecond(serial.runtimeMs.median):0:undefined;const held=Boolean(trace)&&(derivedStep>=traceFinal||extinguished);return <div className={`backend-tile tile-${backend}`} key={backend}><div className="backend-tile-head"><b>{LABELS[backend]}</b><span className={trace?'status-ok':'muted'}>{trace?'Playback ready':'Preparing trace'}</span></div><FireCanvas scenario={trace} frameIndex={index} label={LABELS[backend]}/><div className="tile-meta"><span>{derivedStep.toLocaleString()} derived current step</span><b>{fps.toFixed(1)} steps/s</b></div><div className="tile-meta"><span>{finalDerived.toLocaleString()} derived steps in 5.0 s</span><span>{relative===undefined?'Serial baseline unavailable':`${relative.toFixed(2)}× vs Serial`}</span></div><div className="tile-meta"><span>{held?`Animation held at Step ${visualStep}`:`Animation available through Step ${traceFinal}`}</span><span>{extinguished?`Fire extinguished: first sampled extinguished Step ${extinguishedStep}`:trace?(fire?'Fire active':'Fire not active in current sample'):'Awaiting trace'}</span></div></div>})}</div>
  <div className="trace-caption">Source: {rows}×{rows} · Display: 500×500 · {aggregationForGrid(rows)}×{aggregationForGrid(rows)} cells/pixel · majority base + any-burning overlay</div></section>;
}
